/* eslint-disable @next/next/no-page-custom-font */
import '../styles/tailwind.base.css';

import type { AppProps } from 'next/app';
import Head from 'next/head';

import Header from '../components/Header/Header';
import Sidebar from '../components/Sidebar/Sidebar';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className='flex flex-col flex-no-wrap'>
      <Head>
        <title>Cloning Google Keep</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='anonymous'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=East+Sea+Dokdo&family=Gugi&family=Nanum+Pen+Script&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Header />
      <div className='flex flex-no-wrap'>
        <Sidebar />
        <div className='container mx-auto py-10 h-64 md:w-4/5 w-11/12 px-6'>
          {/* Remove class [ border-dashed border-2 border-gray-300 ] to remove dotted border */}
          <div className='w-full h-full rounded border-dashed border-2 border-gray-300'>
            <Component {...pageProps} />
          </div>
        </div>
      </div>
    </div>
  );
}

export default MyApp;
