import type { NextPage } from 'next';
import Head from 'next/head';

import Sidebar from '../components/Sidebar/Sidebar';
import SidebarItem from '../components/Sidebar/SidebarItem';

const Home: NextPage = ({ children }) => {
  return (
    <div className='flex flex-no-wrap'>
      <Head>
        <title>Cloning Google Keep</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Sidebar />
      <SidebarItem />
      <main>{children}</main>
    </div>
  );
};

export default Home;
